[tool.black]
line-length = 79
skip-string-normalization = true
extend-exclude = 'tests|migrations'
src_paths = ["projectC"]

[tool.isort]
profile = "black"
line_length = 79
src_paths = ["projectC"]
extend_skip = ["tests"]