STICKER_ANGRY_HACKER = r"CAACAgIAAxkBAAEJUN9kie8vQ9yyf-Be508M0BKxHQABAU4AAokKAAJxbolL05dc6IwrA7AvBA"

STICKER_FANNY_HACKER = (
    r"CAACAgIAAxkBAAEJUN1kie8LRkgm_8w4J-R-Ix7_o3HHNAACSgMAArVx2gbCfgb6m0gexC8E"
)

# start block sticker COLD
STICKER_FISH_COLD = (
    r"CAACAgIAAxkBAAEJ2lRkxYMU6_PmnOlUUcvu36p3n8cS7gAChgAD9wLIDw5AaN32E2B9LwQ"
)
STICKER_CROCODILE_COLD = (
    r"CAACAgIAAxkBAAEJ2lZkxYMkC5He35dgD8BSAg2jFSuQWwACIgkAAhhC7giwkQ5lZwxHoC8E"
)
STICKER_DUCK_COLD = (
    r"CAACAgIAAxkBAAEJ2lhkxYNOX3M14i8RVOUpxaaT2pnYngACCQEAAladvQrWZlyD1z-oHS8E"
)
# end block sticker COLD


# start block sticker HOT
STICKER_BEE_HOT = (
    r"CAACAgIAAxkBAAEJ2lpkxYOXl34T6h-HOsrIufU2TMFbqQAC4wwAAjAT0Euml6TE9QhYWy8E"
)
STICKER_FISH_HOT = (
    r"CAACAgIAAxkBAAEJ2nxkxZ0XXaWXYXOUapoVV36uDunwBwACnAAD9wLID3Hmls0qm0LrLwQ"
)
STICKER_LIGHT_HOT = (
    r"CAACAgIAAxkBAAEJ2oBkxZ2sI0g51z2qcOTRErhY0VJfSQACkBAAAmteqEgcGk7MnoBFmC8E"
)
# start block sticker HOT


# start block sticker NO
STICKER_DUCK_NOT = (
    r"CAACAgIAAxkBAAEKLUlk8EOYW5F845CCGN4hrHZjvK5UuQACDAEAAladvQqqb_XSQNziPTAE"
)
STICKER_FISH_NOT = (
    r"CAACAgIAAxkBAAEJ2kFkxX6sd3gN5RP1eJcCYjvI9QtKGQACfQAD9wLIDy7JuwrdyyJJLwQ"
)
STICKER_COON_NOT = (
    r"CAACAgIAAxkBAAEJ2j9kxX6LgZF4k9DTsPbhxKSRp3hIQgACDwwAAuKOOUotFzfMTUK3UC8E"
)
STICKER_DOG_NOT = (
    r"CAACAgEAAxkBAAEKLUtk8EP2fgEnSOHDEGFeIEH0l1q5XQAC8gEAAjgOghFkeRhU3RO6BjAE"
)
STICKER_YELLOW_DOG_NOT = (
    r"CAACAgIAAxkBAAEKLU1k8ERD2EbK11_Tn-3jPBRyZFzZjwACggMAAm2wQgNtUbWjKH5iFzAE"
)
STICKER_FACEPALM_NOT = (
    r"CAACAgIAAxkBAAEKLU9k8ESUr4pdqtjaoIkCovgINFZjfAAC3QAD5KDOB2yVwjLQclMoMAQ"
)
# end block sticker NO


# start block stiker WIN
STICKER_BEE_WIN = (
    r"CAACAgIAAxkBAAEJ2kxkxYHON9eZzPYEavyxGYc1fyQJ5wACAQwAArbpmEtKWijuVpAoPi8E"
)
STICKER_COON_WIN = (
    r"CAACAgIAAxkBAAEJ2k5kxYHw1JVr7FYXBuAL0tVMkZvFJAAC7QIAAvPjvguyApHPzINUli8E"
)
STICKER_CROCODILE_WIN = (
    r"CAACAgIAAxkBAAEJ2lJkxYJjmAnxP5gbgK7vE0kjSzPGHQACGwkAAhhC7gjcuaXV80quyC8E"
)
# end block stiker WIN


NOT_STICKER_LIST = [
    STICKER_COON_NOT,
    STICKER_DUCK_NOT,
    STICKER_FISH_NOT,
    STICKER_DOG_NOT,
    STICKER_YELLOW_DOG_NOT,
    STICKER_FACEPALM_NOT,
]

WIN_STICKER_LIST = [
    STICKER_BEE_WIN,
    STICKER_COON_WIN,
    STICKER_CROCODILE_WIN,
]

HOT_STICKER_LIST = [
    STICKER_BEE_HOT,
    STICKER_FISH_HOT,
    STICKER_LIGHT_HOT,
]

COLD_STICKER_LIST = [
    STICKER_FISH_COLD,
    STICKER_CROCODILE_COLD,
    STICKER_DUCK_COLD,
]
