"""Added account table

Revision ID: 228ecd7e33ae
Revises: 
Create Date: 2024-03-23 02:17:07.094914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228ecd7e33ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binaryconverter',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('total_try', sa.Integer(), nullable=True),
    sa.Column('count_encrypted_characters', sa.Integer(), nullable=True),
    sa.Column('number_decoded_characters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('difficultyhaortpyramid',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_difficulty', sa.Integer(), nullable=True),
    sa.Column('best_result', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guessnumber',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('best_result', sa.Integer(), nullable=True),
    sa.Column('total_number_games', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('haortpyramid',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('total_number_games', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gameprofile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameprofile')
    op.drop_table('users')
    op.drop_table('haortpyramid')
    op.drop_table('guessnumber')
    op.drop_table('difficultyhaortpyramid')
    op.drop_table('binaryconverter')
    # ### end Alembic commands ###
