"""fix game dificulty

Revision ID: 443e3b648445
Revises: 7b8398785148
Create Date: 2024-06-15 19:18:56.316477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443e3b648445'
down_revision: Union[str, None] = '7b8398785148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'binary_converter', ['id'])
    op.create_unique_constraint(None, 'game_profile', ['id'])
    op.create_unique_constraint(None, 'guess_number', ['id'])
    op.drop_constraint('haort_pyramid_game_difficulty_key', 'haort_pyramid', type_='unique')
    op.create_unique_constraint(None, 'haort_pyramid', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'haort_pyramid', type_='unique')
    op.create_unique_constraint('haort_pyramid_game_difficulty_key', 'haort_pyramid', ['game_difficulty'])
    op.drop_constraint(None, 'guess_number', type_='unique')
    op.drop_constraint(None, 'game_profile', type_='unique')
    op.drop_constraint(None, 'binary_converter', type_='unique')
    # ### end Alembic commands ###
