"""fix

Revision ID: e99fba92fe12
Revises: 443e3b648445
Create Date: 2024-06-17 20:07:05.641275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99fba92fe12'
down_revision: Union[str, None] = '443e3b648445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_first_name_key', 'user', type_='unique')
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    op.create_unique_constraint('user_first_name_key', 'user', ['first_name'])
    # ### end Alembic commands ###
